challenges/urls.py
from django.urls import path

from . import views

app_name = "challenges"
urlpatterns = [
    path("explore/", views.home, name="explore"),
    path("challenge/<int:id>/", views.challenge_detail_view, name="detail"),
    path("challenge/random/", views.random_challenge_view, name="random"),
    path(
        "challenge/<int:chal_id>/post/<int:id>/",
        views.post_detail_view,
        name="post_detail",
    ),
    path("challenge/<int:id>/accept", views.accept_challenge, name="accept"),
    path(
        "challenge/<int:id>/finish/<str:action>", views.finish_challenge, name="finish"
    ),
    path(
        "challenge/<int:chal_id>/post/create",
        views.create_challenge_post_view,
        name="create_post",
    ),
    path("post/<int:id>/upvote/", views.challenge_post_upvote, name="post_upvote"),
    path(
        "challenge/<int:chal_id>/post/<int:post_id>/comment/<int:id>",
        views.comment_detail_view,
        name="comment_detail",
    ),
    path(
        "comment/<int:id>/vote/<str:action>/",
        views.comment_vote,
        name="comment_vote",
    ),
]

summerventure/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from users.views import login_view, signup_view, logout_view

urlpatterns = [
    path("", views.landing_page_view, name="landing"),
    path("challenges/", include("challenges.urls")),
    path("users/", include("users.urls")),
    path("login/", login_view, name="login"),
    path("sign-up/", signup_view, name="signup"),
    path("logout/", logout_view, name="logout"),
    path("admin/", admin.site.urls),
]

users/urls.py
from django.urls import path

from .views import user_page

app_name = "users"

urlpatterns = [
    path("user/<int:id>", user_page, name="user_page"),
]

users/models.py
import pathlib
import uuid

from django.conf import settings

from django.db import models

User = settings.AUTH_USER_MODEL
AVATAR_STORAGE_FOLDER = "profile-pics"
AVATAR_DEFAULT_SUFFIX = ".svg"


def avatar_upload_handler(instance, filename):
    file_path = pathlib.Path(filename)
    new_file_name = str(uuid.uuid1())

    return f"{AVATAR_STORAGE_FOLDER}/{new_file_name}{file_path.suffix}"


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    avatar = models.FileField(upload_to=avatar_upload_handler, null=False, blank=False)
    rating = models.PositiveIntegerField(null=False, blank=False, default=0)

    def get_avatar_img(self):
        return f"{self.avatar.url}{AVATAR_DEFAULT_SUFFIX}"

    def get_rank(self):
        if self.rating > 2200:
            return "savior"

        ranks = {
            "recruit": range(0, 100),
            "attendant": range(100, 220),
            "carrier": range(220, 360),
            "messenger": range(360, 520),
            "specialist": range(520, 700),
            "mentor": range(700, 900),
            "adventurer": range(900, 1120),
            "master adventurer": range(1120, 1360),
            "explorer": range(1360, 1620),
            "royal explorer": range(1620, 1900),
            "challenger": range(1900, 2200),
        }

        for rank in ranks.keys():
            if self.rating in ranks[rank]:
                return rank

    def get_nav_rank_class(self):
        return f"nav-rank-{self.get_rank().replace(' ', '')}"

    def get_rank_class(self):
        return f"rank-{self.get_rank().replace(' ', '')}"

challenges/forms.py
from django import forms

from .models import Post

# class PostCreationForm(forms.Form):
#     caption = forms.CharField(
#         label="Caption",
#         max_length=200,
#         widget=forms.Textarea(attrs={"placeholder": "Write a caption"}),
#     )

#     image = forms.ImageField(label="Image")
#     image.widget.attrs.update({"class": "image-input"})

#     def clean(self):
#         cleaned_data = self.cleaned_data
#         return cleaned_data


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["caption", "image"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["caption"].widget = forms.Textarea(
            attrs={"placeholder": "Write a caption"}
        )
        self.fields["image"].widget.attrs.update({"class": "image-input"})


class CommentCreationForm(forms.Form):
    # comment-textarea
    message = forms.CharField(
        max_length=200,
        widget=forms.Textarea(
            attrs={"placeholder": "Write a comment", "class": "comment-textarea"}
        ),
    )

    def clean(self):
        cleaned_data = self.cleaned_data
        return cleaned_data

challenges/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone

from users.models import Profile
from .models import Challenge, Post, Comment, Attempt

from .utils import get_featured_challenges, get_random_challenge
from .forms import CommentCreationForm, PostCreationForm


@login_required
def home(request):
    current_user = request.user
    user_profile = Profile.objects.filter(user=current_user).first()
    challenges = Challenge.objects.all()
    featured_challenges = get_featured_challenges(challenges, 4)

    context = {
        "current_user": current_user,
        "user_profile": user_profile,
        "challenges": challenges,
        "featured_challenges": featured_challenges,
    }

    return render(request, "challenges/home.html", context=context)


@login_required
def challenge_detail_view(request, id):
    current_user = request.user
    user_profile = Profile.objects.filter(user=current_user).first()
    challenge = get_object_or_404(Challenge, pk=id)
    posts = challenge.get_all_posts()

    attempt = Attempt.objects.filter(
        user=request.user, challenge=challenge, status="p"
    ).first()

    if attempt:
        if attempt.expected_end_timestamp <= timezone.now():
            return redirect(challenge.get_challenge_finish_url("failed"))

    context = {
        "current_user": current_user,
        "user_profile": user_profile,
        "challenge": challenge,
        "posts": posts,
        "attempt": attempt,
    }
    return render(request, "challenges/detail.html", context=context)


@login_required
def challenge_post_upvote(request, id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=id)
        post.upvote_post(request.user)
        context = {
            "post": post,
        }

    return render(request, "challenges/partials/post-meta-info.html", context=context)


@login_required
def random_challenge_view(request):
    challenge = get_random_challenge(Challenge.objects.all())
    return redirect(challenge.get_absolute_url())


@login_required
def accept_challenge(request, id):
    challenge = get_object_or_404(Challenge, pk=id)
    attempt = Attempt.objects.filter(
        user=request.user, challenge=challenge, status="p"
    ).first()

    if attempt is not None:
        return redirect(challenge.get_absolute_url())

    Attempt.objects.create(user=request.user, challenge=challenge, status="p")
    return redirect(challenge.get_absolute_url())


@login_required
def finish_challenge(request, id, action):
    challenge = get_object_or_404(Challenge, pk=id)
    attempt = Attempt.objects.filter(
        user=request.user, challenge=challenge, status="p"
    ).first()
    if attempt is None:
        return redirect(challenge.get_absolute_url())

    status = {
        "done": "d",
        "failed": "f",
    }

    attempt.status = status.get(action)
    attempt.actual_end_timestamp = timezone.now()
    attempt.save()
    return redirect(challenge.get_absolute_url())


@login_required
def post_detail_view(request, chal_id, id):
    current_user = request.user
    user_profile = Profile.objects.filter(user=current_user).first()
    challenge = get_object_or_404(Challenge, pk=chal_id)
    post = get_object_or_404(Post, pk=id)
    comments = post.get_all_comments()

    form = CommentCreationForm(data=request.POST or None)

    if form.is_valid():
        message = form.cleaned_data.get("message")
        new_comment = Comment.objects.create(
            user=current_user, post=post, challenge=challenge, message=message
        )
        return redirect(new_comment.get_absolute_url())

    context = {
        "post": post,
        "current_user": current_user,
        "user_profile": user_profile,
        "challenge": challenge,
        "comments": comments,
        "comment_form": form,
    }
    return render(request, "challenges/post-detail.html", context=context)


@login_required
def create_challenge_post_view(request, chal_id):
    challenge = get_object_or_404(Challenge, pk=chal_id)
    current_attempt = Attempt.objects.filter(
        user=request.user, challenge=challenge, status="p"
    ).first()

    if current_attempt is None:
        return redirect(challenge.get_absolute_url())

    if current_attempt.expected_end_timestamp <= timezone.now():
        return redirect(challenge.get_challenge_finish_url("failed"))

    form = PostCreationForm()
    print(form.data)

    if request.method == "POST":
        form = PostCreationForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.challenge = challenge
            new_post.save()

            return redirect(challenge.get_challenge_finish_url("done"))

    context = {
        "challenge": challenge,
        "form": form,
    }
    return render(request, "challenges/post-create.html", context=context)


@login_required
def comment_detail_view(request, chal_id, post_id, id):
    current_user = request.user
    user_profile = Profile.objects.filter(user=current_user).first()
    challenge = get_object_or_404(Challenge, pk=chal_id)
    post = get_object_or_404(Post, pk=post_id)
    parent_comment = get_object_or_404(Comment, pk=id)

    comments = parent_comment.get_all_replies()

    form = CommentCreationForm(data=request.POST or None)

    if form.is_valid():
        message = form.cleaned_data.get("message")
        new_comment = Comment.objects.create(
            user=current_user,
            post=post,
            challenge=challenge,
            parent_comment=parent_comment,
            message=message,
        )
        return redirect(new_comment.get_absolute_url())

    context = {
        "current_user": current_user,
        "user_profile": user_profile,
        "challenge": challenge,
        "post": post,
        "comment": parent_comment,
        "reply_form": form,
        "comments": comments,
    }
    return render(request, "challenges/comment-detail.html", context=context)


@login_required
def comment_vote(request, id, action):
    if request.method == "POST":
        comment = get_object_or_404(Comment, pk=id)
        comment.vote_comment(request.user, action)

        context = {
            "comment": comment,
        }

    return render(
        request, "challenges/partials/comment-meta-info.html", context=context
    )

templates/challenges/comment-detail.html
{% extends 'base.html' %}
{% load static %}

<!-- ------ PAGE IDENTITY ------ -->

{% block title %} {{ comment.message|truncatechars:20 }} {% endblock %}

{% block additional_styles %}
<style>
</style>
{% endblock %}

<!-- ------ PAGE IDENTITY ------ -->

{% block content %}
<a href="{{ post.get_absolute_url }}" class="back-link">
    <img src="{% static 'base/images/icons/arrow-left.svg' %}" alt="" />
    <span>Back</span>
</a>

<div class="comment-detail-container">
    <div href="#" class="comment">
        <div href="#user" class="user-info">
            <a href="#useravatar">
                <img
                    class="user-avatar {{ comment.user.profile_set.first.get_rank_class }}"
                    src="{{ comment.user.profile_set.first.get_avatar_img }}"
                    alt=""
                />
            </a>
            <a href="#username">
                <span class="username">@{{ comment.user.username }}</span>
            </a>
        </div>
        <div class="comment-info">
            <div>
                <p class="caption">{{ comment.message }}</p>
            </div>
        </div>
        {% include 'challenges/partials/comment-meta-info.html' %}
    </div>
</div>

<h1>Comments</h1>
<div class="comment-form-container">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="comment-form-input-container">
            {{ reply_form.message }}
            {{ reply_form.errors }}
            <button type="submit" class="comment-submit">
                Comment
            </button>
        </div>
    </form>
</div>
<div class="comments-container">
    {% if comments %}
        {% for comment in comments %}
            <div href="#" class="comment">
                <div href="#user" class="user-info">
                    <a href="#useravatar">
                        <img
                            class="user-avatar {{ comment.user.profile_set.first.get_rank_class }}"
                            src="{{ comment.user.profile_set.first.get_avatar_img }}"
                            alt=""
                        />
                    </a>
                    <a href="#username">
                        <span class="username">@{{ comment.user.username }}</span>
                    </a>
                </div>
                <div class="comment-info">
                    <a href="#caption">
                        <p class="caption">{{ comment.message }}</p>
                    </a>
                </div>
                {% include 'challenges/partials/comment-meta-info.html' %}
            </div>
        {% endfor %}
    {% else %}
        <h3>Be the first one to comment!</h3>
    {% endif %}
</div>
{% endblock %}

templates/challenges/detail.html
{% extends 'base.html' %}
{% load static %}
<!-- ------ PAGE IDENTITY ------ -->

{% block title %} {{ challenge.title|truncatechars:24 }} {% endblock %}

{% block additional_styles %}
<style>
</style>
{% endblock %}

<!-- ------ PAGE IDENTITY ------ -->

{% block content %}
    <a href="{% url 'challenges:explore' %}" class="back-link">
        <img src="{% static 'base/images/icons/arrow-left.svg' %}" alt="" />
        <span>Back to challenges</span>
    </a>

    <div class="challenge-info">
        <div
            class="challenge-img"
            style="
                background-image: url({{ challenge.get_challenge_image }});
            "
        ></div>
        <h3>{{ challenge.title }}</h3>
        <div class="description">
            <span>Description</span>
            <p>{{ challenge.description }}</p>
        </div>
        <div class="meta-info">
            <p><span>Duration:</span> <span>{{ challenge.duration }} hours</span></p>
            <p>
                <span>Difficulty:</span> <span class="{{ challenge.difficulty_translate }}">{{ challenge.difficulty_translate|capfirst }}</span>
            </p>
            <p><span>Completion Rate:</span> <span>{{ challenge.completion_rate }}%</span></p>
        </div>
        {% if attempt %}
            <a href="{{ challenge.get_challenge_mark_done_url }}">
                <img src="{% static 'base/images/icons/check-circle.svg' %}" alt="" />
                <span>Finished? | Time remaining: {{ attempt.time_remaining }}</span>
            </a>
        {% else %}
            <a href="{{ challenge.get_challenge_accept_url }}">
                <img src="{% static 'base/images/icons/check-circle.svg' %}" alt="" />
                <span>Accept</span>
            </a>
        {% endif %}
    </div>

    <h1>Completers</h1>
    <div class="posts-container">
        {% if posts %}
            {% for post in posts %}
                <div class="post">
                    <div href="#user" class="user-info">
                        <a href="#useravatar">
                            <img
                                class="user-avatar {{ post.user.profile_set.first.get_rank_class }}"
                                src="{{ post.user.profile_set.first.get_avatar_img }}"
                                alt=""
                            />
                        </a>
                        <a href="#username">
                            <span class="username">@{{ post.user.username }}</span>
                        </a>
                    </div>
                    <div class="post-info">
                        <a href="{{ post.get_absolute_url }}">
                            <p class="caption">{{ post.caption }}</p>
                        </a>
                        <a
                            href="{{ post.get_absolute_url }}"
                            class="post-img"
                            style="
                                background-image: url({{ post.image.url }});
                            "
                        ></a>
                    </div>
                    {% include 'challenges/partials/post-meta-info.html' %}
                </div>
            {% endfor %}
        {% else %}
                <h3>No completers yet. Be the first one!</h3>
        {% endif %}
    </div>
{% endblock %}

templates/challenges/home.html
{% extends 'base.html' %} 
{% load static %}
<!-- ------ PAGE IDENTITY ------ -->

{% block title %} Explore {% endblock %}

{% block additional_styles %}
<style>
</style>
{% endblock %}

<!-- ------ PAGE IDENTITY ------ -->

{% block content %}
    <h1>Featured this hour</h1>
    <div class="featured-cards">
        <div class="page-content">
            {% for featured in featured_challenges %}
                <div
                    class="card"
                    style="
                        background-image: url({{ featured.get_featured_image }});
                    "
                >
                    <div class="content">
                        <h2 class="title">{{ featured.title|truncatechars:24 }}</h2>
                        <p class="copy"> {{ featured.description|truncatechars:40 }} </p>
                        <a class="btn" href="{{ featured.get_absolute_url }}">CHECK IT OUT</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <h1>Explore Challenges</h1>
    <div class="challenge-options">
        <a href="{% url 'challenges:random' %}" class="random-btn">
            <img src="{% static 'base/images/icons/shuffle.svg' %}" alt="" />
            <span>Random Challenge</span>
        </a>
    </div>
    <div class="challenges-container">
        {% for challenge in challenges %} 
            <a href="{{ challenge.get_absolute_url }}" class="challenge">
                <h3>{{ challenge.title|truncatechars:40 }}</h3>
                <p class="difficulty">
                    <span>Difficulty:</span> <span class="{{ challenge.difficulty_translate }}">{{ challenge.difficulty_translate|capfirst }}</span>
                </p>
                <p class="completion">
                    <span>Completion rate:</span> <span>{{ challenge.completion_rate }}%</span>
                </p>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/challenges/post-create.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <a href="{{ challenge.get_absolute_url }}" class="back-link">
        <img src="{% static 'base/images/icons/arrow-left.svg' %}" alt="" />
        <span>Back</span>
    </a>

    <h1>Post</h1>
    <div class="post-create-container">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="post-create-input-container">
                <div class="caption-create-container">
                    <p>{{ form.caption.label }}</p>
                    {{ form.caption }}
                </div>
                <div class="upload-image-container">
                    <div class="upload-field-container">
                        <p>{{ form.image.label }}</p>
                        <p class="file-upload">{{ form.image }}</p>
                        {{ form.image.errors }}
                    </div>
                    <p class="help-text">
                        <span>
                            <img src="{% static 'base/images/icons/info.svg' %}" alt="Info" />
                        </span>
                        <span
                            >An image is required because it acts as
                            your proof of completion</span
                        >
                    </p>
                </div>
                <div class="submit-btn-container">
                    <button type="submit">Mark as done</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/challenges/post-detail.html
{% extends 'base.html' %}
{% load static %}

<!-- ------ PAGE IDENTITY ------ -->

{% block title %} {{ post.caption|truncatechars:20 }} {% endblock %}

{% block additional_styles %}
<style>
</style>
{% endblock %}

<!-- ------ PAGE IDENTITY ------ -->

{% block content %}
<a href="{{ challenge.get_absolute_url }}" class="back-link">
    <img src="{% static 'base/images/icons/arrow-left.svg' %}" alt="" />
    <span>Back</span>
</a>

<div href="#user" class="user-info post-detail-user-info">
    <a href="#useravatar">
        <img
            class="user-avatar {{ post.user.profile_set.first.get_rank_class }}"
            src="{{ post.user.profile_set.first.get_avatar_img }}"
            alt=""
        />
    </a>
    <a href="#username">
        <span class="username">{{ post.user.username }}</span>
    </a>
</div>

<div class="post-info post-detail-info">
    <div class="caption">
        <span>Caption</span>
        <p> {{ post.caption }} </p>
    </div>
    <a href="{{ post.image.url }}" target="_blank">
        <div
            class="post-detail-img"
            style="
                background-image: url({{ post.image.url }});
            "
        ></div>
    </a>
    {% include 'challenges/partials/post-meta-info.html' %}
</div>

<h1>Comments</h1>
<div class="comment-form-container">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="comment-form-input-container">
            {{ comment_form.message }}
            {{ comment_form.errors }}
            <button type="submit" class="comment-submit">
                Comment
            </button>
        </div>
    </form>
</div>
<div class="comments-container">
    {% if comments %}
        {% for comment in comments %}
            <div href="{{ comment.get_absolute_url }}" class="comment">
                <div href="#user" class="user-info">
                    <a href="#useravatar">
                        <img
                            class="user-avatar {{ comment.user.profile_set.first.get_rank_class }}"
                            src="{{ comment.user.profile_set.first.get_avatar_img }}"
                            alt=""
                        />
                    </a>
                    <a href="#username">
                        <span class="username">@{{ comment.user.username }}</span>
                    </a>
                </div>
                <div class="comment-info">
                    <a href="{{ comment.get_absolute_url }}">
                        <p class="caption">{{ comment.message }}</p>
                    </a>
                </div>
                {% include 'challenges/partials/comment-meta-info.html' %}
            </div>
        {% endfor %}
    {% else %}
        <h3>Be the first one to comment!</h3>
    {% endif %}
</div>
{% endblock %}